# GNN Kinematics Model Configuration

# Training configuration
training:
  train_mode: true
  use_local_data: true
  random_seed: 42
  batch_size: 32
  learning_rate: 0.001
  n_epochs: 100
  patience: 20
  validation_split: 0.2

# Data configuration
data:
  sample_rate: 200  # Hz
  max_sequence_length: 200
  min_sequence_length: 10

# Data paths (relative to project root)
paths:
  data_dir: "../dataset"
  models_dir: "../models"
  output_dir: "../results/gnn_kinematics"
  train_data: "../dataset/train.csv"
  train_demographics: "../dataset/train_demographics.csv"
  test_data: "../dataset/test.csv"
  test_demographics: "../dataset/test_demographics.csv"

# Gesture classes
gesture_classes:
  - "Above ear - pull hair"
  - "Cheek - pinch skin"
  - "Drink from bottle/cup"
  - "Eyebrow - pull hair"
  - "Eyelash - pull hair"
  - "Feel around in tray and pull out an object"
  - "Forehead - pull hairline"
  - "Forehead - scratch"
  - "Glasses on/off"
  - "Neck - pinch skin"
  - "Neck - scratch"
  - "Pinch knee/leg skin"
  - "Pull air toward your face"
  - "Scratch knee/leg skin"
  - "Text on phone"
  - "Wave hello"
  - "Write name in air"
  - "Write name on leg"

# Demographics features
demographics_features:
  - "adult_child"
  - "age"
  - "sex"
  - "handedness"
  - "height_cm"
  - "shoulder_to_wrist_cm"
  - "elbow_to_wrist_cm"

# Kinematic model parameters
kinematic:
  n_joints: 3  # shoulder, elbow, wrist
  hidden_dim: 128
  gnn_layers: 3
  attention_heads: 4
  dropout: 0.1
  joint_dof: [3, 1, 2]  # Degrees of freedom for each joint
  physics_weight: 0.1  # Weight for physics-based constraints

# Model architecture constants (computed from other values)
model:
  n_classes: 18  # length of gesture_classes
  demo_features_dim: 7  # length of demographics_features